In [1]:
import numpy as np
import matplotlib.pyplot as plt

##### Eigendecomposition

In [2]:
A = np.array([[4, 2],
              [1, 3]])

# Eigendecomposition: A = Q @ Λ @ Q^(-1)
eigenvalues, eigenvectors = np.linalg.eig(A)

Q = eigenvectors
Lambda = np.diag(eigenvalues)
Q_inv = np.linalg.inv(Q)

A_reconstructed = Q @ Lambda @ Q_inv
print(f"Original A:\n{A}")
print(f"\nReconstructed A:\n{A_reconstructed}")
print(f"\nAre they equal? {np.allclose(A, A_reconstructed)}")

Original A:
[[4 2]
 [1 3]]

Reconstructed A:
[[4. 2.]
 [1. 3.]]

Are they equal? True


##### Singular Value Decomposition (SVD)*

#### SVD Background Calculation Logic:
##### SVD: A = **U** @ **λ** @ **V^T**
- 1. For **U** : Calculates (A @ A.T) and finds its Eigenvectors.
- 2. For **Vt**: Calculates (A.T @ A) and finds its Eigenvectors.
- 3. For **S** : Takes the Square Root (√λ) of the Eigenvalues of **U**.

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# SVD: A = U @ Σ @ V^T
U, S, Vt = np.linalg.svd(A)
print(f"U (left singular vectors):\n{U}")
print(f"\nS (singular values): {S}")
print(f"\nV^T (right singular vectors, transposed):\n{Vt}")

Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:len(S), :len(S)] = np.diag(S)
A_reconstructed = U @ Sigma @ Vt

print(f"\nOriginal A:\n{A}")
print(f"\nReconstructed A:\n{A_reconstructed}")
print(f"\nAre they equal? {np.allclose(A, A_reconstructed)}")

U (left singular vectors):
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

S (singular values): [9.508032   0.77286964]

V^T (right singular vectors, transposed):
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]

Original A:
[[1 2 3]
 [4 5 6]]

Reconstructed A:
[[1. 2. 3.]
 [4. 5. 6.]]

Are they equal? True


In [4]:
# Low-rank approximation
A = np.random.randn(100, 100)
original_size = A.size

U, S, Vt = np.linalg.svd(A)

k = 15
U_K = U[:, :k]
S_K = S[:k]
Vt_K = Vt[:k, :]

# Reconstruct
A_approx = U_K @ np.diag(S_K) @ Vt_K
compressed_size = U_K.size + S_K.size + Vt_K.size

print(f"Original size: {original_size}")
print(f"Compressed size: {compressed_size}")
print(f"Compression ratio: {original_size / compressed_size:.2f}x")

Original size: 10000
Compressed size: 3015
Compression ratio: 3.32x


##### QR Decomposition

In [7]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# QR decomposition: A = Q @ R
Q, R = np.linalg.qr(A)

print(f"Q (orthogonal):\n{Q}")
print(f"\nR (upper triangular):\n{R}")

A_reconstructed = Q @ R
print(f"\nOriginal A:\n{A}")
print(f"\nReconstructed A:\n{A_reconstructed}")

Q (orthogonal):
[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]

R (upper triangular):
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]

Original A:
[[1 2]
 [3 4]
 [5 6]]

Reconstructed A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
