In [4]:
import numpy as np
from scipy.linalg import lu
from scipy.linalg import solve

**Gaussian Elimination**

In [ ]:
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
b = np.array([[8],
              [-11],
              [-3]])


augmented = np.hstack([A, b])
print("Augmented matrix [A | b]:")
print(augmented)


P, L, U = lu(A)
print("\nUpper triangular (U) - row echelon form:")
print(U)


x = solve(A, b)
print(f"\nSolution x:\n{x}")

Augmented matrix [A | b]:
[[  2   1  -1   8]
 [ -3  -1   2 -11]
 [ -2   1   2  -3]]

Upper triangular (U) - row echelon form:
[[-3.         -1.          2.        ]
 [ 0.          1.66666667  0.66666667]
 [ 0.          0.          0.2       ]]

Solution x:
[[ 2.]
 [ 3.]
 [-1.]]
