##### Key Takeaways
- Scalars (0D): Single numbers
- Vectors (1D): Arrays of numbers
- Matrices (2D): 2D arrays
- Higher-order tensors (3D+): Multi-dimensional arrays
- Rank: Number of dimensions
- Shape: Size of each dimension
- Axes: Each dimension is an axis
- Essential in Deep Learning: All data in neural networks are tensors

In [1]:
import numpy as np

In [2]:
tensors = [
    np.array(5),
    np.array([1, 2, 3]),
    np.array([[1, 2], [3, 4]]),
    np.random.rand(2, 3, 4)
]

In [3]:
for i, t in enumerate(tensors):
    print(f"Tensor {i}: Rank = {t.ndim}, Shape = {t.shape}")

Tensor 0: Rank = 0, Shape = ()
Tensor 1: Rank = 1, Shape = (3,)
Tensor 2: Rank = 2, Shape = (2, 2)
Tensor 3: Rank = 3, Shape = (2, 3, 4)


In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(f"Sum along axis 0 (columns): {matrix.sum(axis=0)}")

Sum along axis 0 (columns): [5 7 9]


In [6]:
print(f"Sum along axis 1 (rows): {matrix.sum(axis=1)}")

Sum along axis 1 (rows): [ 6 15]


In [7]:
examples = {
    'scalar': np.array(5).shape,
    'vector': np.array([1, 2, 3]).shape,
    'matrix': np.array([[1, 2], [3, 4]]).shape,
    'image': np.random.rand(224, 224, 3).shape,
    'batch_images': np.random.rand(32, 224, 224, 3).shape
}

for name, shape in examples.items():
    print(f"{name}: {shape}")

scalar: ()
vector: (3,)
matrix: (2, 2)
image: (224, 224, 3)
batch_images: (32, 224, 224, 3)


#### Tensor Operations

In [ ]:
# Reshaping
v = np.array([1, 2, 3, 4, 5, 6])
matrix = v.reshape(2, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Flatten
flattened = matrix.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [14]:
# Broadcasting
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector
result

array([[11, 22, 33],
       [14, 25, 36]])

#### Recurrent Neural Networks

In [15]:
batch_size = 32
input_features = 784
hidden_units = 128
output_units = 10

X = np.random.rand(batch_size, input_features)

W1 = np.random.rand(input_features, hidden_units)

hidden = X @ W1

print(f"Input shape: {X.shape}")
print(f"Weight shape: {W1.shape}")
print(f"Output shape: {hidden.shape}")

Input shape: (32, 784)
Weight shape: (784, 128)
Output shape: (32, 128)


In [17]:
# Broadcasting
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix @ vector
result

array([140, 320])