In [ ]:
import tensorflow as tf
import numpy as np

**TensorFlow Tensors**

In [2]:
# Creating tensors
scaler = tf.constant(42)
vector = tf.constant([1, 2, 3, 4])
matrix = tf.constant([[1, 2], [2, 3]])
tensor_3d = tf.constant([[[1, 2], [2, 4]], [[5, 4], [6, 5]]])

print(scaler.shape)
print(vector.shape)
print(matrix.shape)
print(tensor_3d.shape)

()
(4,)
(2, 2)
(2, 2, 2)


In [4]:
# Random tensors
random_tensor = tf.random.normal(shape=(2, 3))  # Normal distribution

uniform_tensor = tf.random.uniform(shape=(2, 3), minval=0, maxval=1)

In [5]:
# Zeros and ones
zeros = tf.zeros(shape=(3, 4))
ones = tf.ones(shape=(3, 4))

**Tensor Variables**

In [7]:
# tf.Variable: Mutable tensors (for model parameters)
weights = tf.Variable(tf.random.normal(shape=(10, 5)))
bias = tf.Variable(tf.zeros(shape=(5,)))

# Update variable
weights.assign_add(tf.random.normal(shape=(10, 5)) * 0.1)

<tf.Variable 'UnreadVariable' shape=(10, 5) dtype=float32, numpy=
array([[-0.95096034,  1.7085471 ,  1.2175797 ,  0.15732184,  0.06668992],
       [ 0.931882  ,  0.26363117, -1.1076436 , -1.5020803 ,  0.04459862],
       [-0.39507222, -0.19324589,  0.9678788 , -0.5355533 ,  1.0042278 ],
       [-0.16845843,  0.33943638, -0.9877686 ,  1.6957504 , -0.32807603],
       [ 1.2797517 ,  0.98243755,  1.2862215 ,  0.5302278 , -1.2027256 ],
       [ 0.56330913, -0.15263872,  0.609606  ,  2.7117667 ,  0.28898552],
       [-0.64376235,  0.90552646,  1.0594523 ,  1.1313848 ,  1.1862597 ],
       [ 0.7886152 ,  0.28388524, -0.39902422, -0.4528887 ,  0.36723977],
       [-0.7806394 , -1.0919663 ,  1.8870076 , -0.31216478,  1.9034301 ],
       [ 0.61827964,  1.6528145 ,  0.0220841 ,  1.6268365 , -0.37831777]],
      dtype=float32)>

**Tensor Operations**

In [8]:
# Matrix multiplication
x = tf.random.normal(shape=(3, 4))
y = tf.random.normal(shape=(4, 5))
z = tf.matmul(x, y)  # or x @ y

print(z)

tf.Tensor(
[[-1.2556368  -0.02974185  0.6834599  -0.8167526  -1.5910243 ]
 [ 0.31417376  2.0340466  -0.36244893  0.7070482   3.5687754 ]
 [ 0.31544903  0.00632469 -0.38602903 -1.2125752   0.18319821]], shape=(3, 5), dtype=float32)


In [9]:
# Element-wise operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
element_wise = a * b
element_wise_sum = a + b

print(f"Element wise multiplication: {element_wise}")
print(f"Element wise sum: {element_wise_sum}")

Element wise multiplication: [[ 5 12]
 [21 32]]
Element wise sum: [[ 6  8]
 [10 12]]


In [10]:
# Aggregation
x = tf.constant([[1, 2, 3], [4, 5, 6]])

print(tf.reduce_mean(x))  # Mean of all elements
print(tf.reduce_sum(x, axis=0))
print(tf.reduce_max(x, axis=1)) 

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


**Tensor Attributes**

In [11]:
tensor = tf.random.normal(shape=(3, 4))

print(f"Shape: {tensor.shape}")
print(f"Rank: {tf.rank(tensor)}")  # Number of dimensions
print(f"Size: {tf.size(tensor)}")  # Total number of elements
print(f"Dtype: {tensor.dtype}")

Shape: (3, 4)
Rank: 2
Size: 12
Dtype: <dtype: 'float32'>


**TensorFlow and NumPy**

In [13]:
# NumPy to TensorFlow
numpy_array = np.array([1, 2, 3])
tf_tensor = tf.constant(numpy_array)

print(tf_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [14]:
# TensorFlow to NumPy
tf_tensor = tf.constant([1, 2, 3, 4])
numpy_array = tf_tensor.numpy()

print(numpy_array)

[1 2 3 4]


**GPU Acceleration**

In [17]:
print(f"GPU Available: {tf.config.list_physical_devices('GPU')}")

# Use GPU if available
if tf.config.list_logical_devices('GPU'):
    with tf.device('/GPU:0'):
        x = tf.random.normal(shape=(1000, 1000))
        y = tf.random.normal(shape=(1000, 1000))
        z = x @ y

GPU Available: []
