In [1]:
import torch
import numpy as np

**Creating tensors**

In [2]:
# Scalar (0D tensor)
scalar = torch.tensor(42)
print(f"Scalar: {scalar}, Shape: {scalar.shape}")

Scalar: 42, Shape: torch.Size([])


In [ ]:
# Vector (1D tensor)
vector = torch.tensor([1, 2, 3])
print(f"Scalar: {vector}, Shape: {vector.shape}")

Scalar: tensor([1, 2, 3]), Shape: torch.Size([3])


In [4]:
# Matrix (2D tensor)
matrix = torch.tensor([[1, 2], [3, 4]])
print(f"Matrix: {matrix}, Shape: {matrix.shape}")

Matrix: tensor([[1, 2],
        [3, 4]]), Shape: torch.Size([2, 2])


In [5]:
# 3D tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Tensor: {tensor_3d}, Shape: {tensor_3d.shape}")

3D Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]), Shape: torch.Size([2, 2, 2])


In [11]:
# Random tensors
random_tensor = torch.rand(3, 4)
normal_tensor = torch.randn(3, 4)
zeros = torch.zeros(3, 4)
ones = torch.ones(2, 3)

print(f"{ones}\n\n{zeros}")

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


**Tensor Data Types**

In [12]:
float32_tensor = torch.tensor([1.0, 2.0], dtype=torch.float32)
int64_tensor = torch.tensor([1, 2], dtype=torch.int64)
bool_tensor = torch.tensor([True, False], dtype=torch.bool)

In [ ]:
print(f"Data type: {float32_tensor.dtype}")
print(f"Shape: {float32_tensor.shape}")

print(f"Device: {float32_tensor.device}")  # cpu or cuda
print(f"Requires grad: {float32_tensor.requires_grad}")  # For autograd

Data type: torch.float32
Shape: torch.Size([2])
Device: cpu
Requires grad: False


**Tensor Attributes**

In [14]:
tensor = torch.randn(3, 4)

print(f"shape : {tensor.shape}")
print(f"Number of dimensions: {tensor.ndim}")
print(f"Number of elements: {tensor.numel()}")
print(f"Data type: {tensor.dtype}")
print(f"Device: {tensor.device}")
print(f"Layout: {tensor.layout}")  # Usually 'strided'

shape : torch.Size([3, 4])
Number of dimensions: 2
Number of elements: 12
Data type: torch.float32
Device: cpu
Layout: torch.strided


**Manipulating Tensors**

In [17]:
# Reshaping
x = torch.randn(4, 4)
x_reshape = x.reshape(2, 8)
x_flattened = x.flatten()

print(f"X shape : {x.shape}")
print(f"After reshape : {x_reshape.shape}")
print(f"Flatten shape: {x_flattened.shape}")
print(f"After Flatten : {x_flattened}")

X shape : torch.Size([4, 4])
After reshape : torch.Size([2, 8])
Flatten shape: torch.Size([16])
After Flatten : tensor([ 0.9740, -0.0408, -0.7522,  2.6091,  0.7594,  1.2502, -0.2742,  0.0933,
         1.1967, -0.2245,  0.9724,  1.1411,  3.0950, -0.9496,  0.3738,  0.2716])


In [19]:
# Stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
stacked = torch.stack([a, b])

print(f"stack : {stacked}")
print(f"shape : {stacked.shape}")

stack : tensor([[1, 2, 3],
        [4, 5, 6]])
shape : torch.Size([2, 3])


In [20]:
# Concatenation
concat = torch.cat([a, b], dim=0)

print(f"concat : {concat}")
print(f"Concat shape : {concat.shape}")

concat : tensor([1, 2, 3, 4, 5, 6])
Concat shape : torch.Size([6])


In [24]:
# Squeezing and Unsqueezing
x = torch.randn(1, 3, 1, 4)
x_squeezed = x.squeeze()
x_unsqueezed = x.unsqueeze(0)

print(f"squeeze shape : {x_squeezed.shape}")
print(f"unsqueeze shape : {x_unsqueezed.shape}")

squeeze shape : torch.Size([3, 4])
unsqueeze shape : torch.Size([1, 1, 3, 1, 4])


In [25]:
# Permuting (transposing)
x = torch.randn(2, 3, 4)
x_permuted = x.permute(2, 0, 1) # New shape: (4, 2, 3)

**Matrix Multiplication**

In [26]:
# Matrix multiplication
x = torch.randn(3, 4)
y = torch.randn(4, 5)
z = torch.matmul(x, y)  # or x @ y
print(f"Result shape: {z.shape}")  

Result shape: torch.Size([3, 5])


In [ ]:
# Element-wise operations
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

element_wise = a * b
element_wise_sum = a + b

print(element_wise)
print(element_wise_sum.shape)

tensor([[ 5, 12],
        [21, 32]])
torch.Size([2, 2])


**Finding Min, Max, Mean, Sum**

In [33]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)

print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
print(f"Min along dim 0: {x.min(dim=0)}")

print(f"Argmin: {x.argmin()}")  # Index of minimum
print(f"Argmax: {x.argmax()}")  # Index of maximum

Min: 1.0
Max: 6.0
Min along dim 0: torch.return_types.min(
values=tensor([1., 2., 3.], dtype=torch.float64),
indices=tensor([0, 0, 0]))
Argmin: 0
Argmax: 5


In [34]:
print(f"Mean: {x.mean()}")
print(f"Sum: {x.sum()}")
print(f"Mean along dim 1: {x.mean(dim=1)}")
print(f"Sum along dim 0: {x.sum(dim=0)}")

Mean: 3.5
Sum: 21.0
Mean along dim 1: tensor([2., 5.], dtype=torch.float64)
Sum along dim 0: tensor([5., 7., 9.], dtype=torch.float64)


**PyTorch and NumPy Interoperability**

In [35]:
# NumPy to PyTorch
numpy_array = np.array([1, 2, 3, 4])
torch_tensor = torch.from_numpy(numpy_array) 

In [36]:
# PyTorch to NumPy
torch_tensor = torch.tensor([1, 2, 3, 4])
numpy_array = torch_tensor.numpy()

In [ ]:
# If tensor is on GPU, need to move to CPU first
numpy_array = torch_tensor.cpu().numpy()

**Reproducibility**

In [37]:
# Set random seed for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# For CUDA
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)
    
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

**Accessing GPU and Device-Agnostic Code**

In [38]:
# Check GPU availability
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cpu


In [ ]:
# Move tensor to device
x = torch.randn(3, 4)
x_gpu = x.to(device)

In [ ]:
# Device-agnostic code (best practice)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = NeuralNetwork().to(device)
data = data.to(device)

In [40]:
# Check CUDA device properties
if torch.cuda.is_available():
    print(f"CUDA Device: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")