In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Creating matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(f"Matrix A:\n{A}")
print(f"Shape: {A.shape}") # 2 rows, 3 columns
print(f"Size: {A.size}")
print(f"Rank: {A.ndim}")

Matrix A:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Rank: 2


In [7]:
# Special matrices

# Zero matrix
zeros = np.zeros((3, 3))
print(f"Zero matrix:\n{zeros}\n")

# Identity matrix
I = np.eye(3)
print(f"Identity matrix:\n{I}\n")

# Ones matrix
ones = np.ones((2, 3))
print(f"Ones matrix:\n{ones}\n")

Zero matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ones matrix:
[[1. 1. 1.]
 [1. 1. 1.]]



#### Matrix Operations

In [12]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Element-wise addition
C = A + B
print(f"A + B =\n{C}\n")

# Element-wise subtraction
D = A - B
print(f"A - B =\n{D}")

5 + 12 + 21 + 32

A + B =
[[ 6  8]
 [10 12]]

A - B =
[[-4 -4]
 [-4 -4]]


- Commutative? NO! A @ B ≠ B @ A (in general)
- Associative? YES! (A @ B) @ C = A @ (B @ C)
- Distributive? YES! A @ (B + C) = A @ B + A @ C

In [16]:
# Scalar Multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])


# C = np.dot(A, B)
C = A @ B
print(f"A @ B =\n{C}")

A @ B =
[[19 22]
 [43 50]]


In [17]:
# Demonstrate non-commutativity
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

AB = A @ B
BA = B @ A

print(f"A @ B =\n{AB}")
print(f"\nB @ A =\n{BA}")
print(f"\nAre they equal? {np.array_equal(AB, BA)}")

A @ B =
[[19 22]
 [43 50]]

B @ A =
[[23 34]
 [31 46]]

Are they equal? False


In [19]:
# Matrix-Vector Multiplication

A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([1, 2, 3])

result = A @ v
print(f"A @ v = {result}")

# result[0] = A[0,0]*v[0] + A[0,1]*v[1] + A[0,2]*v[2] = 1*1 + 2*2 + 3*3 = 14
# result[1] = A[1,0]*v[0] + A[1,1]*v[1] + A[1,2]*v[2] = 4*1 + 5*2 + 6*3 = 32

A @ v = [14 32]


In [20]:
# Transpose

A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_T = A.T
print(f"\nA^T =\n{A_T}")

# Properties:
# (A^T)^T = A
# (A + B)^T = A^T + B^T
# (AB)^T = B^T @ A^T


A^T =
[[1 4]
 [2 5]
 [3 6]]


In [21]:
# Matrix Inverse
A = np.array([[1, 2],
              [3, 4]])

# Inverse (only for square, non-singular matrices)
A_inv = np.linalg.inv(A)
print(f"A^(-1) =\n{A_inv}")

A^(-1) =
[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
# Verify: A @ A^(-1) = I
I = A @ A_inv
print(f"A @ A^(-1) =\n{I}")

A @ A^(-1) =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
